sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.10.50
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tGJKWuBifboPQrMQFze
    access-key-secret: PghR2lcWRjJI4UupdqLtPVXCIz9INS
    bucket-name: linkeda

  redis:
    host: 192.168.10.50
    port: 6379
    #password: 123456
    database: 10
